# Generated by Django 5.1.4 on 2024-12-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de vivienda')),
                ('zona', models.CharField(max_length=50, verbose_name='Zona')),
                ('dormitorios', models.PositiveIntegerField(verbose_name='Número de dormitorios')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio en USD')),
                ('tamaño', models.PositiveIntegerField(verbose_name='Tamaño en metros cuadrados')),
                ('extras', models.TextField(blank=True, null=True, verbose_name='Extras o características adicionales')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='viviendas/', verbose_name='Foto de la vivienda')),
            ],
        ),
    ]
